### ISSUE TITLE
Screems take up blog count

### ISSUE THREAD

**Issue by NateBrune** [NateBrune/Screem#2]
With the current system, every time a user "screems" they use one out of there 5 blogs they are allowed per day. I propose a system where every month a new top level post is posted in the #screem category and every user of screem auto-upvotes it when they sign into the service. Once logged in, if the user decides to screem, there screem will go in as a comment to the initial root post. The auto-upvoting is needed because if the top level post makes no money, the comment's make no money.

This has a couple of benefits:
- Posts are no longer counted as blogs
- Posts are no longer eating your blog count
- It gives me a revenue model for expanding and maintaining the website
- It almost doesn't change the existing system at all

**Comment by faddat** [comment]
I second this.  

I love how the revenue model is merely a side-effect.

**screem on!**

**Comment by NateBrune** [comment]
@faddat This has been implemented. Look for a post in 12 hours introducing squeek.io

**Comment by f3rnando** [comment]
Simple but great idea!
